# Generated by Django 5.1.3 on 2024-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image1_alter_post_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image1',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
