# Generated by Django 5.1.3 on 2024-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_image',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
