# Generated by Django 5.1.3 on 2024-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_notfound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qatgadir/')),
            ],
        ),
    ]
