# Generated by Django 5.1.3 on 2024-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_page_notfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentlar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
