# Generated by Django 5.1.3 on 2024-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_description_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
